apiVersion: config.istio.io/v1alpha2
kind: listchecker
metadata:
  name: whitelist-for-ratings
  namespace: default
spec:
  overrides: ["reviews"]  # overrides provide a static list
  blacklist: false
---
apiVersion: config.istio.io/v1alpha2
kind: listentry
metadata:
  name: applabel
  namespace: default
spec:
  value: source.labels["app"]
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: checksourceapp
  namespace: default
spec:
  match: destination.labels["app"] == "ratings"
  actions:
  - handler: whitelist-for-ratings.listchecker
    instances:
    - applabel.listentry
